project_id = "thzdazcmswmeolaiijml"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://localhost:5173"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[functions.freshdesk-sync]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.send-custom-email]
verify_jwt = false

[functions.process-incoming-email]
verify_jwt = false

[functions.test-mail-connection]
verify_jwt = false

[functions.fetch-pop3-emails]
verify_jwt = false

[functions.process-pending-emails]
verify_jwt = false

[functions.yeastar-auth]
verify_jwt = false

[functions.yeastar-contacts]
verify_jwt = false

[functions.yeastar-users]
verify_jwt = false

[functions.yeastar-tickets]
verify_jwt = false